[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Bold" }
italic = { family = "IBM Plex Mono", style = "Italic" }
bold_italic = { family = "IBM Plex Mono", style = "Bold Italic" }

size = 11.0

# Optional: You can specify additional font settings
# offset = { x = 0, y = 0 }
# glyph_offset = { x = 0, y = 0 }

# Set to true if you want to use the built-in box drawing characters
builtin_box_drawing = true

# You can also specify different fonts for specific unicode ranges
# [font.normal]
# family = "IBM Plex Mono"
# style = "Regular"

# [font.glyph_offset]
# x = 0
# y = 0

# Additional font-related settings can be added here
